---
driver:
  name: docker 
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: ryuzee/ubuntu_chef:12.04
  - name: centos-6.4
    driver_config:
      image: ryuzee/centos_chef:6.4

suites:
  - name: default
    run_list:
      - recipe[ntp::default]
    attributes:
